set -e

CC=x86_64-essence-gcc
CFLAGS="-I../../../ports/acpica/include -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=kernel -g -Wno-unused-parameter -mno-red-zone"

# mkdir essrc
# cp source/components/dispatcher/* essrc
# cp source/components/events/* essrc
# cp source/components/executer/* essrc
# cp source/components/hardware/* essrc
# cp source/components/namespace/* essrc
# cp source/components/parser/* essrc
# cp source/components/resources/* essrc
# cp source/components/tables/* essrc
# cp source/components/utilities/* essrc
# cd essrc

$CC -c dsargs.c      $CFLAGS
$CC -c dscontrol.c   $CFLAGS
$CC -c dsdebug.c     $CFLAGS
$CC -c dsfield.c     $CFLAGS
$CC -c dsinit.c      $CFLAGS
$CC -c dsmethod.c    $CFLAGS
$CC -c dsmthdat.c    $CFLAGS
$CC -c dsobject.c    $CFLAGS
$CC -c dsopcode.c    $CFLAGS
$CC -c dspkginit.c   $CFLAGS
$CC -c dsutils.c     $CFLAGS
$CC -c dswexec.c     $CFLAGS
$CC -c dswload2.c    $CFLAGS
$CC -c dswload.c     $CFLAGS
$CC -c dswscope.c    $CFLAGS
$CC -c dswstate.c    $CFLAGS
$CC -c evevent.c     $CFLAGS
$CC -c evglock.c     $CFLAGS
$CC -c evgpeblk.c    $CFLAGS
$CC -c evgpe.c       $CFLAGS
$CC -c evgpeinit.c   $CFLAGS
$CC -c evgpeutil.c   $CFLAGS
$CC -c evhandler.c   $CFLAGS
$CC -c evmisc.c      $CFLAGS
$CC -c evregion.c    $CFLAGS
$CC -c evrgnini.c    $CFLAGS
$CC -c evsci.c       $CFLAGS
$CC -c evxface.c     $CFLAGS
$CC -c evxfevnt.c    $CFLAGS
$CC -c evxfgpe.c     $CFLAGS
$CC -c evxfregn.c    $CFLAGS
$CC -c exconcat.c    $CFLAGS
$CC -c exconfig.c    $CFLAGS
$CC -c exconvrt.c    $CFLAGS
$CC -c excreate.c    $CFLAGS
$CC -c exdebug.c     $CFLAGS
$CC -c exdump.c      $CFLAGS
$CC -c exfield.c     $CFLAGS
$CC -c exfldio.c     $CFLAGS
$CC -c exmisc.c      $CFLAGS
$CC -c exmutex.c     $CFLAGS
$CC -c exnames.c     $CFLAGS
$CC -c exoparg1.c    $CFLAGS
$CC -c exoparg2.c    $CFLAGS
$CC -c exoparg3.c    $CFLAGS
$CC -c exoparg6.c    $CFLAGS
$CC -c exprep.c      $CFLAGS
$CC -c exregion.c    $CFLAGS
$CC -c exresnte.c    $CFLAGS
$CC -c exresolv.c    $CFLAGS
$CC -c exresop.c     $CFLAGS
$CC -c exserial.c    $CFLAGS
$CC -c exstore.c     $CFLAGS
$CC -c exstoren.c    $CFLAGS
$CC -c exstorob.c    $CFLAGS
$CC -c exsystem.c    $CFLAGS
$CC -c extrace.c     $CFLAGS
$CC -c exutils.c     $CFLAGS
$CC -c hwacpi.c      $CFLAGS
$CC -c hwesleep.c    $CFLAGS
$CC -c hwgpe.c       $CFLAGS
$CC -c hwpci.c       $CFLAGS
$CC -c hwregs.c      $CFLAGS
$CC -c hwsleep.c     $CFLAGS
$CC -c hwtimer.c     $CFLAGS
$CC -c hwvalid.c     $CFLAGS
$CC -c hwxface.c     $CFLAGS
$CC -c hwxfsleep.c   $CFLAGS
$CC -c nsaccess.c    $CFLAGS
$CC -c nsalloc.c     $CFLAGS
$CC -c nsarguments.c $CFLAGS
$CC -c nsconvert.c   $CFLAGS
$CC -c nsdump.c      $CFLAGS
$CC -c nsdumpdv.c    $CFLAGS
$CC -c nseval.c      $CFLAGS
$CC -c nsinit.c      $CFLAGS
$CC -c nsload.c      $CFLAGS
$CC -c nsnames.c     $CFLAGS
$CC -c nsobject.c    $CFLAGS
$CC -c nsparse.c     $CFLAGS
$CC -c nspredef.c    $CFLAGS
$CC -c nsprepkg.c    $CFLAGS
$CC -c nsrepair2.c   $CFLAGS
$CC -c nsrepair.c    $CFLAGS
$CC -c nssearch.c    $CFLAGS
$CC -c nsutils.c     $CFLAGS
$CC -c nswalk.c      $CFLAGS
$CC -c nsxfeval.c    $CFLAGS
$CC -c nsxfname.c    $CFLAGS
$CC -c nsxfobj.c     $CFLAGS
$CC -c psargs.c      $CFLAGS
$CC -c psloop.c      $CFLAGS
$CC -c psobject.c    $CFLAGS
$CC -c psopcode.c    $CFLAGS
$CC -c psopinfo.c    $CFLAGS
$CC -c psparse.c     $CFLAGS
$CC -c psscope.c     $CFLAGS
$CC -c pstree.c      $CFLAGS
$CC -c psutils.c     $CFLAGS
$CC -c pswalk.c      $CFLAGS
$CC -c psxface.c     $CFLAGS
$CC -c rsaddr.c      $CFLAGS
$CC -c rscalc.c      $CFLAGS
$CC -c rscreate.c    $CFLAGS
$CC -c rsinfo.c      $CFLAGS
$CC -c rsio.c        $CFLAGS
$CC -c rsirq.c       $CFLAGS
$CC -c rslist.c      $CFLAGS
$CC -c rsmemory.c    $CFLAGS
$CC -c rsmisc.c      $CFLAGS
$CC -c rsserial.c    $CFLAGS
$CC -c rsutils.c     $CFLAGS
$CC -c rsxface.c     $CFLAGS
$CC -c tbdata.c      $CFLAGS
$CC -c tbfadt.c      $CFLAGS
$CC -c tbfind.c      $CFLAGS
$CC -c tbinstal.c    $CFLAGS
$CC -c tbprint.c     $CFLAGS
$CC -c tbutils.c     $CFLAGS
$CC -c tbxface.c     $CFLAGS
$CC -c tbxfload.c    $CFLAGS
$CC -c tbxfroot.c    $CFLAGS
$CC -c utaddress.c   $CFLAGS
$CC -c utalloc.c     $CFLAGS
$CC -c utascii.c     $CFLAGS
$CC -c utbuffer.c    $CFLAGS
$CC -c utcache.c     $CFLAGS
$CC -c utclib.c      $CFLAGS
$CC -c utcopy.c      $CFLAGS
$CC -c utdebug.c     $CFLAGS
$CC -c utdecode.c    $CFLAGS
$CC -c utdelete.c    $CFLAGS
$CC -c uterror.c     $CFLAGS
$CC -c uteval.c      $CFLAGS
$CC -c utexcep.c     $CFLAGS
$CC -c utglobal.c    $CFLAGS
$CC -c uthex.c       $CFLAGS
$CC -c utids.c       $CFLAGS
$CC -c utinit.c      $CFLAGS
$CC -c utlock.c      $CFLAGS
$CC -c utmath.c      $CFLAGS
$CC -c utmisc.c      $CFLAGS
$CC -c utmutex.c     $CFLAGS
$CC -c utnonansi.c   $CFLAGS
$CC -c utobject.c    $CFLAGS
$CC -c utosi.c       $CFLAGS
$CC -c utownerid.c   $CFLAGS
$CC -c utpredef.c    $CFLAGS
$CC -c utprint.c     $CFLAGS
$CC -c utresdecode.c $CFLAGS
$CC -c utresrc.c     $CFLAGS
$CC -c utstate.c     $CFLAGS
$CC -c utstring.c    $CFLAGS
$CC -c utstrsuppt.c  $CFLAGS
$CC -c utstrtoul64.c $CFLAGS
$CC -c uttrack.c     $CFLAGS
$CC -c utuuid.c      $CFLAGS
$CC -c utxface.c     $CFLAGS
$CC -c utxferror.c   $CFLAGS
$CC -c utxfinit.c    $CFLAGS
$CC -c utxfmutex.c   $CFLAGS

x86_64-essence-ar -rcs libacpica.a dsargs.o dscontrol.o dsdebug.o dsfield.o dsinit.o dsmethod.o dsmthdat.o dsobject.o dsopcode.o dspkginit.o dsutils.o dswexec.o dswload2.o dswload.o dswscope.o dswstate.o evevent.o evglock.o evgpeblk.o evgpe.o evgpeinit.o evgpeutil.o evhandler.o evmisc.o evregion.o evrgnini.o evsci.o evxface.o evxfevnt.o evxfgpe.o evxfregn.o exconcat.o exconfig.o exconvrt.o excreate.o exdebug.o exdump.o exfield.o exfldio.o exmisc.o exmutex.o exnames.o exoparg1.o exoparg2.o exoparg3.o exoparg6.o exprep.o exregion.o exresnte.o exresolv.o exresop.o exserial.o exstore.o exstoren.o exstorob.o exsystem.o extrace.o exutils.o hwacpi.o hwesleep.o hwgpe.o hwpci.o hwregs.o hwsleep.o hwtimer.o hwvalid.o hwxface.o hwxfsleep.o nsaccess.o nsalloc.o nsarguments.o nsconvert.o nsdump.o nsdumpdv.o nseval.o nsinit.o nsload.o nsnames.o nsobject.o nsparse.o nspredef.o nsprepkg.o nsrepair2.o nsrepair.o nssearch.o nsutils.o nswalk.o nsxfeval.o nsxfname.o nsxfobj.o psargs.o psloop.o psobject.o psopcode.o psopinfo.o psparse.o psscope.o pstree.o psutils.o pswalk.o psxface.o rsaddr.o rscalc.o rscreate.o rsinfo.o rsio.o rsirq.o rslist.o rsmemory.o rsmisc.o rsserial.o rsutils.o rsxface.o tbdata.o tbfadt.o tbfind.o tbinstal.o tbprint.o tbutils.o tbxface.o tbxfload.o tbxfroot.o utaddress.o utalloc.o utascii.o utbuffer.o utcache.o utclib.o utcopy.o utdebug.o utdecode.o utdelete.o uterror.o uteval.o utexcep.o utglobal.o uthex.o utids.o utinit.o utlock.o utmath.o utmisc.o utmutex.o utnonansi.o utobject.o utosi.o utownerid.o utpredef.o utprint.o utresdecode.o utresrc.o utstate.o utstring.o utstrsuppt.o utstrtoul64.o uttrack.o utuuid.o utxface.o utxferror.o utxfinit.o utxfmutex.c   

cp libacpica.a ../../../ports/acpica
